<?php
/** @var $block \Encomage\GuestBook\Block\Container */
?>
<div class="guest-book-main-button">
    <button type="button" class="js-show-form" data-logged="<?= (bool)$block->isAllowed() ?>">
        <span><?= /* @escapeNotVerified */ __('Leave a comment'); ?></span>
    </button>
    <span class="js-show-message" hidden><?= /* @escapeNotVerified */ __('Only registered users can post comments'); ?></span>
</div>
<div class="guest-book-list"></div>
<div class="question-form">
    <?= /* @escapeNotVerified */ $block->getFormBlock()->toHtml() ?>
</div>
<script type="text/x-magento-init">
        {
            "*": {
                "guestBookComments": {"listingAjaxUrl": "<?= /* @escapeNotVerified */ $block->escapeUrl($block->getListingUrl()); ?>"}
            }
        }
</script>