<?php
/** @var \Encomage\GuestBook\Block\Comments\Answer  $block */
/** @var \Encomage\GuestBook\Model\GuestBook        $answer */
/** @var \Encomage\GuestBook\Block\Comments\Form    $formBlock */
/** @var \Encomage\GuestBook\Helper\Config          $configHelper */

?>
<?php
$answer = $block->getAnswer();
$formBlock = $block->getFormBlock()
    ->setMessageId((int)$answer->getMessageId())
    ->setReplyPath($answer->getReplyPath());
$configHelper = $this->helper('Encomage\GuestBook\Helper\Config');
$marginContainer = count(explode('/', $answer->getReplyPath())) * 20;
?>
<div class="answer-item" data-margin="<?= /* @escapeNotVerified */ $marginContainer; ?>">
    <div class="attribute">
        <div class="answer-name">
            <span><?= $block->escapeHtml($answer->getName()); ?></span>
        </div>
        <div class="answer-create-date">
            <span><?= $block->escapeHtml($answer->getCreatedAt()); ?></span>
        </div>
        <div class="answer-reply-container">
            <a data-message="<?= $block->escapeHtml((int)$answer->getMessageId()); ?>"
               class="js-answer-reply-open"><?= /* @escapeNotVerified */ __('Reply'); ?></a>
            <a data-message="<?= $block->escapeHtml((int)$answer->getMessageId()); ?>"
               class="js-answer-reply-close answer-reply-close"><?= /* @escapeNotVerified */ __('Reply'); ?></a>
        </div>
        <?php if ($answer->getStatus() === Encomage\GuestBook\Model\GuestBook\Source\Status::STATUS_PENDING): ?>
            <div class="approval">
                <?= /* @escapeNotVerified */ __('This post will become public after administrator approval') ?>
            </div>
        <?php endif; ?>
    </div>
    <h4><?= $block->escapeHtml($answer->getSubject()); ?></h4>
    <div class="message">
        <span><?= $block->escapeHtml($answer->getMessage()); ?></span>
    </div>
    <?php $rating = $answer->getCustomerReview() * 20; ?>
    <div class="product-reviews-summary<?= !$rating ? ' no-rating' : '' ?>" itemprop="aggregateRating">
        <?php if ($rating): ?>
            <div class="rating-summary">
                <span class="label"><span><?= /* @escapeNotVerified */ __('Rating') ?>:</span></span>
                <div class="rating-result" title="<?= $block->escapeHtmlAttr($rating); ?>%">
                    <span style="width:<?= $block->escapeHtmlAttr($rating); ?>%"></span>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <div class="js-reply-form-container-<?= $block->escapeHtml((int)$answer->getMessageId()); ?>" hidden="hidden">

        <?= $formBlock->toHtml() ?>
    </div>
</div>
<?php if ($answer->getAdminAnswer()): ?>
    <div class="admin-answer">
        <?php if ($configHelper->getAdministrationName()): ?>
            <div class="admin-name">
                <?= $block->escapeHtml($configHelper->getAdministrationName()) ?>
            </div>
            <div class="answer-date">
                <span><?= $block->escapeHtml($answer->getCreatedAt()); ?></span>
            </div>
        <?php endif; ?>
        <div class="message">
            <?= $block->escapeHtml($answer->getAdminAnswer()); ?>
        </div>
    </div>
<?php endif; ?>